fps: 60
brightness: 1.00
resolution: '1280x720'
distance: 1.0
fov: 1
transparency: 1.0
smearing: 0.0
powersave: false
clip_context: true
background: '#000'
keep_mapping_bounds: true
border: 0
border_mode: 'parent'
border_color: '#fff'
border_speed: 'half'

display_visibility: 'visible'
display_speed: 'quarter'
display_visible: false
display_video: 0
display_mapping: ''
display_static: false
display_transparent: false
display_noborder: false
display_zindex: 0
display_mask_shape: off
display_keepbounds: true
display_mask: ''
display_smearing: 0.0

trigger_display_visibility: false
force_display_visibility: false
reset_display_visibility: false

perspective0_zoom: 1.0
perspective0_fov: 1
perspective0_angle: 0

perspective1_zoom: 1.0
perspective1_fov: 1
perspective1_angle: 0

perspective2_zoom: 1.0
perspective2_fov: 1
perspective2_angle: 0