_apply: &_apply
  apply: false
  index: 0

_addons: &_addons
  audio: false
  stepwise: false
  oscillate: 'off'

#ripple:
#  << : [*_apply]
#  time:
#    value: 1.0
#    _type: [-10, 10, 0.01]
#    << : [*_addons]
#  speed_scale:
#    value: 1.0
#    _type: [1, 64, 1]
#    << : [*_addons]
#  frequency_scale:
#    value: 50.0
#    _type: [0.1, 512, 0.1]
#    << : [*_addons]
#  amplitude_scale:
#    value: 0.1
#    _type: [0.01, 3, 0.001]
#    << : [*_addons]

#spheredisplacement:
#  << : [*_apply]
#  time:
#    value: 1.0
#    _type: [-3, 3, 0.001]
#    << : [*_addons]
#
#blackhole:
#  << : [*_apply]
#  time:
#    value: 1.0
#    _type: [-3, 3, 0.001]
#    << : [*_addons]
#  scale:
#    value: 1.0
#    _type: [0.01, 5.0, 0.01]
#    << : [*_addons]
#  strength:
#    value: 0.25
#    _type: [0.0, 5, 0.01]
#    << : [*_addons]

#badtv:
#  << : [*_apply]
#  time:
#    value: 1.0
#    _type: [-10, 10, 0.01]
#    << : [*_addons]
#  distortion:
#    value: 3.0
#    _type: [-50, 50, 0.01]
#    << : [*_addons]
#  distortion2:
#    value: 5.0
#    _type: [-50, 50, 0.01]
#    << : [*_addons]
#  speed:
#    value: 0.2
#    _type: [0.1, 2, 0.01]
#    << : [*_addons]
#  rollSpeed:
#    value: 0.1
#    _type: [0.1, 2, 0.01]
#    << : [*_addons]

#rainbow:
#  << : [*_apply]
#  time:
#    value: 1.0
#    _type: [-4.0, 4.0, 0.01]
#    << : [*_addons]
#
#  threshold:
#    value: 1.0
#    _type: [0, 2, 0.01]
#    << : [*_addons]

#colorify:
#  << : [*_apply]
#  color:
#    r:
#      value: 1
#      _type: [0, 2, 0.01]
#      << : [*_addons]
#    g:
#      value: 1
#      _type: [0, 2, 0.01]
#      << : [*_addons]
#    b:
#      value: 1
#      _type: [0, 2, 0.01]
#      << : [*_addons]

#colorstep:
#  << : [*_apply]
